### PR TITLE
fix not to include SIGTERM and SIGCHLD in the signal mask of child processes spawned from the logger process

### PR DESCRIPTION
**Pull request by pandax381**
Fixed so that signal mask changes made in the logger process are not continuation over to the child process.

fix #16

### CODE REVIEW

**Comment by pandax381** [comment]
@monkburger How about this fix?

**Comment by monkburger** [comment]
> @monkburger How about this fix?

Will test it out ASAP. Thanks!

**Comment by monkburger** [comment]
@pandax381 seems to be working. I can manually send SIGTERM to our logging program and it restarts as well.

I'll close #16 in the meantime.

Also, I might have a better solution instead of using Linux-only prctl(PR_SET_PDEATHSIG, SIGKILL) that will work across all platforms.

**Comment by pandax381** [comment]
Thanks for confirming!

I would appreciate getting a new pull request for the prctl().

**Pull request merged**
